prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: go-deploy-lab
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - go-deploy-lab
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            regex: go-deploy-lab
            action: keep
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            regex: http
            action: keep
